#!/bin/bash

# sysinfo_page - Moves relevant files to correct server base directory

if [ -z $1 ]; then
    echo "No minecraft version given (ex: 1.11.2)"
    exit 2
fi

if [ -z $2 ]; then
    echo "No server directory name given (ex: myserver)"
    exit 2
fi


from="forge_stores/$1/."
to="../servers/$2"
jarfile="minecraft-forge-$1.jar"
serverfile="minecraft_server.$1.jar"
servercreated=true


if [ ! -f "$jarfile" ]; then
  echo "Cannot continue as you have not downloaded the jar file for the server by going to multicraft settings->update minecraft"
  exit
fi

if [ ! -d "forge_stores/$1" ]; then
  echo "Cannot continue as library files do not exist for version '$1'"
  exit
fi

if [ ! -d "forge_stores/$1/libraries" ]; then
  echo "Cannot continue as library files do not exist for version '$1'"
  exit
fi

if [ ! -f "forge_stores/$1/$serverfile" ]; then
  echo "Cannot continue as server file does not exist within the library for version '$1'"
  exit
fi


if [ ! -d "$to" ]; then
 echo "The server base directory '$2' does not exist, creating it now, but be sure to use it as the base directory in your multicraft server config."
  mkdir -p $to
  servercreated=false
fi


cp -a "$from" "$to"
cp -a "minecraft-forge-$1.jar" $to

echo "Your files and folders have now been copied"

if [ "$servercreated" = false ]; then
 echo "Dont forget in multicraft when creating this server, set the base dir as '$2'"
fi
